CREATE TABLE IF NOT EXISTS urls (
 id CHAR(6) PRIMARY KEY,
 origin_url VARCHAR(255) NOT NULL UNIQUE,
 url TEXT NOT NULL UNIQUE,
 create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
GRANT ALL PRIVILEGES ON table urls to postgres;
